/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.OrderMenu;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronak
 */
public class MenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    private Restaurant restaurant;
    private OrderMenu dishes;
    public MenuJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        populateMenuTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuInfo = new javax.swing.JLabel();
        scrollCustomerInfo = new javax.swing.JScrollPane();
        tblMenus = new javax.swing.JTable();
        lblManageMenuInfo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblDishName = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblDishDescription = new javax.swing.JLabel();
        lblDishPrice = new javax.swing.JLabel();
        txtDishDescription = new javax.swing.JTextField();
        txtDishPrice = new javax.swing.JTextField();
        txtDishName = new javax.swing.JTextField();
        btnCreateMenu = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 174, 65));

        lblMenuInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMenuInfo.setForeground(new java.awt.Color(102, 51, 255));
        lblMenuInfo.setText("Menu Information");

        tblMenus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblMenus.setForeground(new java.awt.Color(153, 153, 255));
        tblMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollCustomerInfo.setViewportView(tblMenus);

        lblManageMenuInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblManageMenuInfo.setForeground(new java.awt.Color(102, 51, 255));
        lblManageMenuInfo.setText("Add Menu");

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDishName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDishName.setText("Name:");

        btnDelete.setBackground(new java.awt.Color(153, 153, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblDishDescription.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDishDescription.setText("Description:");

        lblDishPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDishPrice.setText("Price:");

        btnCreateMenu.setBackground(new java.awt.Color(153, 153, 255));
        btnCreateMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCreateMenu.setText("Add");
        btnCreateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(350, 350, 350)
                        .addComponent(lblManageMenuInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDishName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDishDescription)
                                .addGap(30, 30, 30)
                                .addComponent(txtDishDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDishPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDishPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnCreateMenu))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(scrollCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(lblMenuInfo)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblManageMenuInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDishName)
                    .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDishDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDishDescription))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDishPrice)
                    .addComponent(txtDishPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateMenu)
                .addGap(11, 11, 11)
                .addComponent(lblMenuInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMenus.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_CANCEL_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete the selected Dish?", "warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                String menuName = (String) tblMenus.getValueAt(selectedRow, 0);
                String dishDescription = (String) tblMenus.getValueAt(selectedRow, 1);
                String deshPrice = (String) tblMenus.getValueAt(selectedRow, 2);
                Restaurant restro = ecosystem.getRestaurantDirectory().getRestaurant(userAccount.getUsername());
                OrderMenu dish = restro.getOneDish(menuName);
                restro.getDishesList().remove(dish);
                populateMenuTable();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMenuActionPerformed
        // TODO add your handling code here:
        if (txtDishName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dish Name cannot be empty.");
            return;
        }
        if (txtDishDescription.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dish Description cannot be empty.");
            return;
        } else if (txtDishPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dish Price cannot be empty.");
            return;
        }
        String numberFormat = "^\\d{0,8}(\\.\\d{1,4})?$";
        if (Pattern.compile(numberFormat).matcher(txtDishPrice.getText()).matches()) {
        } else {
            JOptionPane.showMessageDialog(this, "Dish Price entered is not proper, please enter the price in correct format.");
            return;
        }
        Restaurant restro = ecosystem.getRestaurantDirectory().getRestaurant(userAccount.getUsername());

        String menuName = txtDishName.getText();
        String dishDescripption = txtDishDescription.getText();
        String dishPrice = txtDishPrice.getText();
        OrderMenu menu = new OrderMenu(menuName, dishDescripption, dishPrice);
        restro.getDishesList().add(menu);
        txtDishName.setText("");
        txtDishDescription.setText("");
        txtDishPrice.setText("");
        populateMenuTable();
    }//GEN-LAST:event_btnCreateMenuActionPerformed

    public void populateMenuTable() {
        Restaurant restaurant = ecosystem.getRestaurantDirectory().getRestaurant(userAccount.getUsername());
        DefaultTableModel dishModel = (DefaultTableModel) tblMenus.getModel();
        dishModel.setRowCount(0);
        for (OrderMenu dishes : restaurant.getDishesList()) {
            Object[] row = new Object[5];
            row[0] = dishes.getDishName();
            row[1] = dishes.getDishDescripton();
            row[2] = dishes.getPrice();
            dishModel.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateMenu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel lblDishDescription;
    private javax.swing.JLabel lblDishName;
    private javax.swing.JLabel lblDishPrice;
    private javax.swing.JLabel lblManageMenuInfo;
    private javax.swing.JLabel lblMenuInfo;
    private javax.swing.JScrollPane scrollCustomerInfo;
    private javax.swing.JTable tblMenus;
    private javax.swing.JTextField txtDishDescription;
    private javax.swing.JTextField txtDishName;
    private javax.swing.JTextField txtDishPrice;
    // End of variables declaration//GEN-END:variables
}
