/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ronak
 */
public class DeliveryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    private DeliveryMan deliverymanAccount;
    
    public DeliveryJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        populateDelTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        txtDeliverymanPassword = new javax.swing.JTextField();
        btnCreateDeliveryman = new javax.swing.JButton();
        lblDeliverymanInfo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        scrollDeliverymanInfo = new javax.swing.JScrollPane();
        tblDeliveryman = new javax.swing.JTable();
        lblDeliverymanName = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblDeliverymanPassword = new javax.swing.JLabel();
        lblDeliverymanUsername = new javax.swing.JLabel();
        txtDeliverymanName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        txtDeliverymanUsername = new javax.swing.JTextField();
        lblDeliverymanAddress = new javax.swing.JLabel();
        txtDeliverymanAddress = new javax.swing.JTextField();
        lblDeliverymanNumber = new javax.swing.JLabel();
        txtDeliverymanNumber = new javax.swing.JTextField();
        lblManageDeliverymanInfo1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 174, 65));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtDeliverymanPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        btnCreateDeliveryman.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCreateDeliveryman.setText("Register");
        btnCreateDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDeliverymanActionPerformed(evt);
            }
        });

        lblDeliverymanInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDeliverymanInfo.setText("Deliveryman Information");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblDeliveryman.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tblDeliveryman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Password", "Deliveryman Address", "Deliveryman Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollDeliverymanInfo.setViewportView(tblDeliveryman);

        lblDeliverymanName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDeliverymanName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeliverymanName.setText("Name:");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblDeliverymanPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDeliverymanPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeliverymanPassword.setText("Password:");

        lblDeliverymanUsername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDeliverymanUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeliverymanUsername.setText("Username:");

        txtDeliverymanName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtDeliverymanUsername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblDeliverymanAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDeliverymanAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeliverymanAddress.setText("Address:");

        txtDeliverymanAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblDeliverymanNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblDeliverymanNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDeliverymanNumber.setText("Number:");

        txtDeliverymanNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        lblManageDeliverymanInfo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageDeliverymanInfo1.setText("Create Deliveryman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDeliverymanName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDeliverymanUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDeliverymanPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeliverymanName, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeliverymanUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeliverymanPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDeliverymanAddress)
                                .addGap(26, 26, 26)
                                .addComponent(txtDeliverymanAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDeliverymanNumber)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeliverymanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(btnCreateDeliveryman))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnBack)
                        .addGap(329, 329, 329)
                        .addComponent(lblManageDeliverymanInfo1)))
                .addGap(0, 450, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollDeliverymanInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(307, 307, 307)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(lblDeliverymanInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblManageDeliverymanInfo1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliverymanName)
                    .addComponent(txtDeliverymanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliverymanUsername)
                    .addComponent(txtDeliverymanUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliverymanPassword)
                    .addComponent(txtDeliverymanPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliverymanAddress)
                    .addComponent(txtDeliverymanAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliverymanNumber)
                    .addComponent(txtDeliverymanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateDeliveryman)
                .addGap(18, 18, 18)
                .addComponent(lblDeliverymanInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollDeliverymanInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1089, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateDelTable() {
        DefaultTableModel deliverymanModel = (DefaultTableModel) tblDeliveryman.getModel();
        deliverymanModel.setRowCount(0);
        for(DeliveryMan deliveryMan: ecosystem.getDeliveryManDirectory().getDeliverymanList()) {
                Object[] row = new Object[5];
                row[0] = deliveryMan.getDeliverymanName();
                row[1] = deliveryMan.getDeliverymanUsername();
                row[2] = deliveryMan.getDeliverymanPassword();
                row[3] = deliveryMan.getDeliverymanAddress();
                row[4] = deliveryMan.getDeliverymanNumber();
                deliverymanModel.addRow(row);
        }
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(txtDeliverymanName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Name cannot be empty.");
            return;
        }
        if(txtDeliverymanUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username cannot be empty.");
            return;
        }
        if(txtDeliverymanPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password cannot be empty.");
            return;
        }
        if(txtDeliverymanAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Adress cannot be empty.");
            return;
        }
        else if(txtDeliverymanNumber.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Phone number cannot be empty.");
            return;
        }
        String numberFormat = "^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$";
        if (Pattern.compile(numberFormat).matcher(txtDeliverymanNumber.getText()).matches()) {
            System.out.println("Phone number entered is correct.");
        } else {
            JOptionPane.showMessageDialog(this, "Phone Number entered is not proper, please enter the number in correct format.");
            return;
        }

        ecosystem.getUserAccountDirectory().saveUserAccount(userAccount, txtDeliverymanName.getText(), txtDeliverymanUsername.getText(), txtDeliverymanPassword.getText());
        ecosystem.getDeliveryManDirectory().updateDeliveryman(deliverymanAccount, txtDeliverymanName.getText(), txtDeliverymanUsername.getText(), txtDeliverymanPassword.getText(), txtDeliverymanAddress.getText(), txtDeliverymanNumber.getText());
        populateDelTable();
        txtDeliverymanName.setText("");
        txtDeliverymanUsername.setText("");
        txtDeliverymanPassword.setText("");
        txtDeliverymanAddress.setText("");
        txtDeliverymanNumber.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCreateDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDeliverymanActionPerformed
        // TODO add your handling code here:
        if(txtDeliverymanName.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Name cannot be empty.");
            return;
        }
        if(txtDeliverymanUsername.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Username cannot be empty.");
            return;
        }
        if(txtDeliverymanPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Password cannot be empty.");
            return;
        }
        if(txtDeliverymanAddress.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Adress cannot be empty.");
            return;
        }
        else if(txtDeliverymanNumber.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Phone number cannot be empty.");
            return;
        }
        String numberFormat = "^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$";
        if (Pattern.compile(numberFormat).matcher(txtDeliverymanNumber.getText()).matches()) {
            System.out.println("Phone number entered is correct.");
        } else {
            JOptionPane.showMessageDialog(this, "Phone Number entered is not proper, please enter the number in correct format.");
            return;
        }

        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtDeliverymanUsername.getText())) {
            UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(txtDeliverymanUsername.getText(), txtDeliverymanPassword.getText(), null, new DeliverManRole());
            DeliveryMan deliveryMan = ecosystem.getDeliveryManDirectory().createDeliveryMan(txtDeliverymanName.getText(), txtDeliverymanUsername.getText(), txtDeliverymanPassword.getText(), txtDeliverymanAddress.getText(), txtDeliverymanNumber.getText());
            populateDelTable();
            txtDeliverymanName.setText("");
            txtDeliverymanUsername.setText("");
            txtDeliverymanPassword.setText("");
            txtDeliverymanAddress.setText("");
            txtDeliverymanNumber.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Please enter a unique Username for the Deliveryman.");
        }
    }//GEN-LAST:event_btnCreateDeliverymanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDeliveryman.getSelectedRow();
        if(selectedRow >= 0) {
            String deliverymanName = (String) tblDeliveryman.getValueAt(selectedRow, 0);
            String deliverymanUsername = (String) tblDeliveryman.getValueAt(selectedRow, 1);
            String deliverymanPassword = (String) tblDeliveryman.getValueAt(selectedRow, 2);
            String deliverymanAddress = (String) tblDeliveryman.getValueAt(selectedRow, 3);
            String deliverymanNumber = (String) tblDeliveryman.getValueAt(selectedRow, 4);
            userAccount = ecosystem.getUserAccountDirectory().authenticateUser(deliverymanUsername, deliverymanPassword);
            deliverymanAccount = ecosystem.getDeliveryManDirectory().getDeliveryMan(deliverymanUsername);
            txtDeliverymanName.setText(deliverymanName+ "");
            txtDeliverymanUsername.setText(deliverymanUsername+ "");
            txtDeliverymanPassword.setText(deliverymanPassword+ "");
            txtDeliverymanAddress.setText(deliverymanAddress+ "");
            txtDeliverymanNumber.setText(deliverymanNumber+ "");
        }
        else {
            JOptionPane.showMessageDialog(null, "Please click on the Save button to update the changes.");
        }
        JOptionPane.showMessageDialog(null, "Please select a row to update the Deliveryman User Account.");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDeliveryman.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_CANCEL_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete the selected User Account?", "warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                String deliverymanName = (String) tblDeliveryman.getValueAt(selectedRow, 0);
                String deliverymanUsername = (String) tblDeliveryman.getValueAt(selectedRow, 1);
                String deliverymanPassword = (String) tblDeliveryman.getValueAt(selectedRow, 2);
                String deliverymanAddress = (String) tblDeliveryman.getValueAt(selectedRow, 3);
                String deliverymanNumber = (String) tblDeliveryman.getValueAt(selectedRow, 4);
                UserAccount userAccount = ecosystem.getUserAccountDirectory().authenticateUser(deliverymanUsername, deliverymanPassword);
                DeliveryMan deliveryManAccount = ecosystem.getDeliveryManDirectory().getDeliveryMan(deliverymanUsername);
                ecosystem.getUserAccountDirectory().deleteUserAccount(userAccount);
                ecosystem.getDeliveryManDirectory().deleteDeliveryMan(deliveryManAccount.getDeliverymanUsername());
                populateDelTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete Deliveryman Useraccount.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateDeliveryman;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeliverymanAddress;
    private javax.swing.JLabel lblDeliverymanInfo;
    private javax.swing.JLabel lblDeliverymanName;
    private javax.swing.JLabel lblDeliverymanNumber;
    private javax.swing.JLabel lblDeliverymanPassword;
    private javax.swing.JLabel lblDeliverymanUsername;
    private javax.swing.JLabel lblManageDeliverymanInfo1;
    private javax.swing.JScrollPane scrollDeliverymanInfo;
    private javax.swing.JTable tblDeliveryman;
    private javax.swing.JTextField txtDeliverymanAddress;
    private javax.swing.JTextField txtDeliverymanName;
    private javax.swing.JTextField txtDeliverymanNumber;
    private javax.swing.JTextField txtDeliverymanPassword;
    private javax.swing.JTextField txtDeliverymanUsername;
    // End of variables declaration//GEN-END:variables
}
