/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Restaurant.Order;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAccount;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = business;
      
        
        populateDelTable();
    }
    
    public void populateDelTable(){
        
        DefaultTableModel deliveryInfoTable = (DefaultTableModel) tblDeliveryInfo.getModel();
        deliveryInfoTable.setRowCount(0);
        DeliveryMan deliveryMan = ecosystem.getDeliveryManDirectory().getDeliveryMan(userAccount.getUsername());
        for (Order order : deliveryMan.getOrderList()) {
            Object[] row = new Object[6];
            row[0] = order;
            row[1] = order.getRestaurantName();
            row[2] = order.getCustomerName();
            row[3] = order.getDeliveryAddress();
            row[4] = order.getTotalPrice();
            row[5] = order.getStatus();
            deliveryInfoTable.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblDeliveryInfo = new javax.swing.JTable();
        processJButton1 = new javax.swing.JButton();
        refreshJButton1 = new javax.swing.JButton();
        lblManageDelivery = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 174, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDeliveryInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Restaurant Name", "Customer Name", "Customer Address", "Total Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDeliveryInfo);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 700, 190));

        processJButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        processJButton1.setText("Process Order");
        processJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButton1ActionPerformed(evt);
            }
        });
        add(processJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        refreshJButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        refreshJButton1.setText("Refresh");
        refreshJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton1ActionPerformed(evt);
            }
        });
        add(refreshJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        lblManageDelivery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageDelivery.setText("Manage Delivery");
        add(lblManageDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButton1ActionPerformed

        int selectedRow = tblDeliveryInfo.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row to process the Order.");
        }
        Order order = (Order)tblDeliveryInfo.getValueAt(selectedRow, 0);
        ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, order, ecosystem);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_processJButton1ActionPerformed

    private void refreshJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton1ActionPerformed
        populateDelTable();
    }//GEN-LAST:event_refreshJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblManageDelivery;
    private javax.swing.JButton processJButton1;
    private javax.swing.JButton refreshJButton1;
    private javax.swing.JTable tblDeliveryInfo;
    // End of variables declaration//GEN-END:variables
}
