/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import static java.lang.Boolean.FALSE;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.Config;

/**
 *
 * @author ronak
 */
public class CreateJPanel extends javax.swing.JPanel {
    
//    CarDirectory carDirectory ;
    Car car ;

    /**
     * Creates new form CreateJPanel
     */
//    List<Car> carObjList= new ArrayList<>();
    public CreateJPanel(Car car) {
        initComponents();
    
//        this.carDirectory = carDirectory;
          this.car = car;
          getAllDataCarDtlsForGrid(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CAR_SERIAL_NO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MANUFACTURE_BY = new javax.swing.JTextField();
        MANUFACTURE_YEAR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MODEL_NO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LOCATION = new javax.swing.JComboBox<>();
        deleteCarBtn = new javax.swing.JButton();
        addCarBtn = new javax.swing.JButton();
        editCarBtn = new javax.swing.JButton();
        clearCarFormBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fleetDtlsTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        checkYes = new javax.swing.JCheckBox();
        checkNo = new javax.swing.JCheckBox();
        lblAvail = new javax.swing.JLabel();
        lblCarSeatNo = new javax.swing.JLabel();
        CAR_SEAT_NO = new javax.swing.JTextField();
        lblMainCerti = new javax.swing.JLabel();
        checkValid = new javax.swing.JCheckBox();
        checkInvalid = new javax.swing.JCheckBox();
        lastUpdate = new javax.swing.JLabel();
        lastUpdateValue = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FLEET MANAGEMENT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("Car Serial No.");

        CAR_SERIAL_NO.setToolTipText("");
        CAR_SERIAL_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAR_SERIAL_NOActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Manufacture By.");

        MANUFACTURE_BY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANUFACTURE_BYActionPerformed(evt);
            }
        });

        MANUFACTURE_YEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANUFACTURE_YEARActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Manufacture Year");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 153, 255));
        jLabel5.setText("Model No.");

        MODEL_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODEL_NOActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 153, 255));
        jLabel6.setText("Location");

        LOCATION.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cambridge", "Quincy", "Waltham", "Plymouth" }));

        deleteCarBtn.setBackground(new java.awt.Color(153, 204, 255));
        deleteCarBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteCarBtn.setText("DELETE");
        deleteCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCarBtnMouseClicked(evt);
            }
        });
        deleteCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCarBtnActionPerformed(evt);
            }
        });

        addCarBtn.setBackground(new java.awt.Color(153, 204, 255));
        addCarBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addCarBtn.setText("ADD");
        addCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCarBtnMouseClicked(evt);
            }
        });
        addCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarBtnActionPerformed(evt);
            }
        });

        editCarBtn.setBackground(new java.awt.Color(153, 204, 255));
        editCarBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editCarBtn.setText("UPDATE");
        editCarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCarBtnMouseClicked(evt);
            }
        });

        clearCarFormBtn.setBackground(new java.awt.Color(153, 204, 255));
        clearCarFormBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearCarFormBtn.setText("CLEAR");
        clearCarFormBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearCarFormBtnMouseClicked(evt);
            }
        });

        fleetDtlsTable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fleetDtlsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Car Serial No.", "Mnf By", "Mnf Year", "Model No.", "Location", "Car Seat No.", "Availability", "Maint Certi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        fleetDtlsTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        fleetDtlsTable.setRowHeight(25);
        fleetDtlsTable.setSelectionBackground(new java.awt.Color(102, 153, 255));
        fleetDtlsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fleetDtlsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fleetDtlsTable);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 153, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("FLEET DETAILS");

        buttonGroup1.add(checkYes);
        checkYes.setText("Yes");

        buttonGroup1.add(checkNo);
        checkNo.setText("No");

        lblAvail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAvail.setForeground(new java.awt.Color(102, 153, 255));
        lblAvail.setText("Availability");

        lblCarSeatNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCarSeatNo.setForeground(new java.awt.Color(102, 153, 255));
        lblCarSeatNo.setText("No. Of Seats");

        CAR_SEAT_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAR_SEAT_NOActionPerformed(evt);
            }
        });

        lblMainCerti.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainCerti.setForeground(new java.awt.Color(102, 153, 255));
        lblMainCerti.setText("Maintenance Certificate");

        buttonGroup2.add(checkValid);
        checkValid.setText("Valid");

        buttonGroup2.add(checkInvalid);
        checkInvalid.setText("Invalid");

        lastUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastUpdate.setForeground(new java.awt.Color(102, 153, 255));
        lastUpdate.setText("Updated Timestamp");

        btnUpload.setBackground(new java.awt.Color(153, 204, 255));
        btnUpload.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUploadMouseClicked(evt);
            }
        });
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MANUFACTURE_BY))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CAR_SERIAL_NO))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LOCATION, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCarSeatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CAR_SEAT_NO)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMainCerti, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MANUFACTURE_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MODEL_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(checkYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkNo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(checkValid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkInvalid))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(195, Short.MAX_VALUE)
                        .addComponent(lastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lastUpdateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246)))
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(addCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(editCarBtn)
                .addGap(152, 152, 152)
                .addComponent(deleteCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(clearCarFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CAR_SERIAL_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MANUFACTURE_BY, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MANUFACTURE_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MODEL_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(checkYes)
                                .addComponent(checkNo)
                                .addComponent(lblAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CAR_SEAT_NO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LOCATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMainCerti, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkValid)
                            .addComponent(checkInvalid)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCarSeatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastUpdateValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearCarFormBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CAR_SERIAL_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAR_SERIAL_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAR_SERIAL_NOActionPerformed

    private void MANUFACTURE_BYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANUFACTURE_BYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MANUFACTURE_BYActionPerformed

    private void MANUFACTURE_YEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANUFACTURE_YEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MANUFACTURE_YEARActionPerformed

    private void MODEL_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODEL_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MODEL_NOActionPerformed

    private void deleteCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCarBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) fleetDtlsTable.getModel();
        int selectedRowIndex=fleetDtlsTable.getSelectedRow();

        if(selectedRowIndex == -1){
            JOptionPane.showMessageDialog(this, "Select data from table grid which needs to be deleted.");
        }else{
            //with array
            String selectedTableDBIndex=model.getValueAt(selectedRowIndex, 0).toString();
            model.removeRow(selectedRowIndex);
            MainJFrame.carObjList.remove(selectedRowIndex);
            getAllDataCarDtlsForGrid();
            clearInputField();
            lastUpdate.setText(new Date().toString());
        }
    }//GEN-LAST:event_deleteCarBtnMouseClicked

    private boolean isInputValid(boolean isEdit) {
        String validationMessage = "";
        if (!isEdit && MainJFrame.carObjList.stream().filter(
            (Car c) -> c.getCarSerialNo().equals(
                CAR_SERIAL_NO.getText())).count() != 0) {
            validationMessage += "Car with this serial number already exists.";
        }
        try {
            int seatNumber = Integer.parseInt(CAR_SEAT_NO.getText());
            if (seatNumber < 4 || seatNumber > 9) {
                validationMessage += "\nSeat no. should be between 3 and 9.";
            }
        } catch (NumberFormatException iae) {
            validationMessage += "\nSeat no. must be an integer value.";
        }



        if (MANUFACTURE_YEAR.getText().length() != 4) {
            validationMessage += "\nManufacture year must be in the "
                + "format YYYY.";
        } else {
            try {
                Integer.parseInt(MANUFACTURE_YEAR.getText());
            } catch (NumberFormatException iae) {
                validationMessage += "\nManufacture year must be a valid year";
            }
        }
        System.out.println("validationMessagevalidationMessagevalidationMessagevalidationMessagevalidationMessage");
        
        if (CAR_SERIAL_NO.getText().isBlank()) {
            validationMessage += "\nCar serial no. cannot be blank.";
        }
        if (MANUFACTURE_BY.getText().isBlank()) {
            validationMessage += "\nManufactured by field cannot be blank.";
        }
        if (MODEL_NO.getText().isBlank()) {
            validationMessage += "\nModel no. cannot be blank.";
        }
        if (MANUFACTURE_YEAR.getText().isBlank()) {
            validationMessage += "\nManufacture Year cannot be blank.";
        }
        if (CAR_SEAT_NO.getText().isBlank()) {
            validationMessage += "\nCar Seat Number cannot be blank.";
        }


        if (validationMessage.length() > 0) {
            JOptionPane.showMessageDialog(this, validationMessage);
            return false;
        }
        return true;
}
    private void addCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCarBtnMouseClicked

          if (isInputValid(false)) {
            try {
                //               CAR_SERIAL_NO.getText();
                //               MANUFACTURE_BY.getText();
                //               MANUFACTURE_YEAR.getText();
                //               MODEL_NO.getText().isEmpty();
//                Car car = carDirectory.addNewCar();
                Car carObj = new Car();
                carObj.setId(MainJFrame.carObjList.size() + 1);
                carObj.setCarSerialNo(CAR_SERIAL_NO.getText());
                carObj.setManufactureBy(MANUFACTURE_BY.getText());
                carObj.setManufactureYear(MANUFACTURE_YEAR.getText());
                carObj.setModelNo(MODEL_NO.getText());
                carObj.setLocation(LOCATION.getSelectedItem().toString());
                carObj.setNoOfSeats(Integer.parseInt(CAR_SEAT_NO.getText()));
                if (checkYes.isSelected()) {
                    //  JOptionPane.showMessageDialog(this, yesChecked.getText());
                    carObj.setCarAvail(Boolean.TRUE);
                } else {
                    //   JOptionPane.showMessageDialog(this, noChecked.getText());
                    carObj.setCarAvail(Boolean.FALSE);
                }
                if (checkValid.isSelected()) {
                    //  JOptionPane.showMessageDialog(this, validChecked.getText());
                    carObj.setMainCerti(Boolean.TRUE);
                } else {
                    //   JOptionPane.showMessageDialog(this, invalidChecked.getText());
                    carObj.setMainCerti(Boolean.FALSE);
                }
                MainJFrame.carObjList.add(carObj);

                getAllDataCarDtlsForGrid();
                clearInputField();
                JOptionPane.showMessageDialog(this, "New Car Added Successfully");
                lastUpdateValue.setText(new Date().toString());
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Something went wrong. Please Contact support");
            }
        }  
    }//GEN-LAST:event_addCarBtnMouseClicked

    private void editCarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCarBtnMouseClicked
        DefaultTableModel model = (DefaultTableModel) fleetDtlsTable.getModel();
        int selectedRowIndex=fleetDtlsTable.getSelectedRow();
        if(selectedRowIndex == -1){
            JOptionPane.showMessageDialog(this, "Select data from table grid which needs to be edited.");
        }
        if (isInputValid(true)){
            try{
                //with array
                String serialNo=CAR_SERIAL_NO.getText();
                String MANUFACTUREBY=MANUFACTURE_BY.getText();
                String MANUFACTUREYEAR=MANUFACTURE_YEAR.getText();
                MainJFrame.carObjList.get(selectedRowIndex).setCarSerialNo(CAR_SERIAL_NO.getText());
                MainJFrame.carObjList.get(selectedRowIndex).setManufactureBy(MANUFACTURE_BY.getText());
                MainJFrame.carObjList.get(selectedRowIndex).setManufactureYear(MANUFACTURE_YEAR.getText());
                MainJFrame.carObjList.get(selectedRowIndex).setModelNo(MODEL_NO.getText());
                MainJFrame.carObjList.get(selectedRowIndex).setLocation(LOCATION.getSelectedItem().toString());
                MainJFrame.carObjList.get(selectedRowIndex).setNoOfSeats(Integer.parseInt(CAR_SEAT_NO.getText()));
                if (checkYes.isSelected()) {
               // JOptionPane.showMessageDialog(this, yesChecked.getText());
                    MainJFrame.carObjList.get(selectedRowIndex).setCarAvail(Boolean.TRUE);
               } else {
               // JOptionPane.showMessageDialog(this, noChecked.getText());
                    MainJFrame.carObjList.get(selectedRowIndex).setCarAvail(Boolean.FALSE);
               }
               if (checkValid.isSelected()) {
               // JOptionPane.showMessageDialog(this, validChecked.getText());
                    MainJFrame.carObjList.get(selectedRowIndex).setMainCerti(Boolean.TRUE);
               } else {
               // JOptionPane.showMessageDialog(this, invalidChecked.getText());
                    MainJFrame.carObjList.get(selectedRowIndex).setMainCerti(Boolean.FALSE);
               }
                getAllDataCarDtlsForGrid();
                JOptionPane.showMessageDialog(this, "Data updated successfully");
                clearInputField();
                lastUpdateValue.setText(new Date().toString());
            }catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Something went wrong. Please Contact support");
            }

        }
    }//GEN-LAST:event_editCarBtnMouseClicked

    private void clearCarFormBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearCarFormBtnMouseClicked
        clearInputField();
    }//GEN-LAST:event_clearCarFormBtnMouseClicked

    private void clearInputField(){
        CAR_SERIAL_NO.setText("");
        MANUFACTURE_BY.setText("");
        MANUFACTURE_YEAR.setText("");
        MODEL_NO.setText("");
        CAR_SEAT_NO.setText("");
        LOCATION.setSelectedItem("Cambridge");
        checkYes.setSelected(FALSE);
        checkNo.setSelected(FALSE);
        checkValid.setSelected(FALSE);
        checkInvalid.setSelected(FALSE);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }
    
    private void fleetDtlsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fleetDtlsTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) fleetDtlsTable.getModel();
        int selectedRowIndex=fleetDtlsTable.getSelectedRow();

        CAR_SERIAL_NO.setText(model.getValueAt(selectedRowIndex, 1).toString());
        MANUFACTURE_BY.setText(model.getValueAt(selectedRowIndex, 2).toString());
        MANUFACTURE_YEAR.setText(model.getValueAt(selectedRowIndex, 3).toString());
        MODEL_NO.setText(model.getValueAt(selectedRowIndex, 4).toString());
        LOCATION.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString());
        CAR_SEAT_NO.setText(model.getValueAt(selectedRowIndex, 6).toString());
        if (model.getValueAt(selectedRowIndex, 7).toString().equals("Yes")) {
            checkYes.setSelected(true);
        } else {
            checkNo.setSelected(true);
        }



        if (model.getValueAt(selectedRowIndex, 8).toString().equals("Valid")) {
            checkValid.setSelected(true);
        } else {
            checkInvalid.setSelected(true);
        }
    }//GEN-LAST:event_fleetDtlsTableMouseClicked

    private void CAR_SEAT_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAR_SEAT_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAR_SEAT_NOActionPerformed

    private void deleteCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCarBtnActionPerformed

    private void addCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarBtnActionPerformed
       
        
        
    }//GEN-LAST:event_addCarBtnActionPerformed

    private void btnUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadMouseClicked

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        Config fleetConfig = new Config();
        fleetConfig.uploadData();
        getAllDataCarDtlsForGrid();
    }//GEN-LAST:event_btnUploadActionPerformed

    public void getAllDataCarDtlsForGrid(){
        try{
            //with array
            DefaultTableModel model = (DefaultTableModel) fleetDtlsTable.getModel();
            model.setRowCount(0);
            Object rowData[]=new Object[9];
            for(int index=0;index<MainJFrame.carObjList.size();index++){
                Integer id=MainJFrame.carObjList.get(index).getId();
                System.out.println("ID "+id);
                rowData[0]=MainJFrame.carObjList.get(index).getId();
                rowData[1]=MainJFrame.carObjList.get(index).getCarSerialNo();
                rowData[2]=MainJFrame.carObjList.get(index).getManufactureBy();
                rowData[3]=MainJFrame.carObjList.get(index).getManufactureYear();
                rowData[4]=MainJFrame.carObjList.get(index).getModelNo();
                rowData[5]=MainJFrame.carObjList.get(index).getLocation();
                rowData[6]=MainJFrame.carObjList.get(index).getNoOfSeats();
                rowData[7]=MainJFrame.carObjList.get(index).getCarAvail() ? "Yes" : "No";
                rowData[8]=MainJFrame.carObjList.get(index).getMainCerti() ? "Valid" : "Invalid";
                model.addRow(rowData);
            }
          
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CAR_SEAT_NO;
    private javax.swing.JTextField CAR_SERIAL_NO;
    private javax.swing.JComboBox<String> LOCATION;
    private javax.swing.JTextField MANUFACTURE_BY;
    private javax.swing.JTextField MANUFACTURE_YEAR;
    private javax.swing.JTextField MODEL_NO;
    private javax.swing.JButton addCarBtn;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkInvalid;
    private javax.swing.JCheckBox checkNo;
    private javax.swing.JCheckBox checkValid;
    private javax.swing.JCheckBox checkYes;
    private javax.swing.JButton clearCarFormBtn;
    private javax.swing.JButton deleteCarBtn;
    private javax.swing.JButton editCarBtn;
    private javax.swing.JTable fleetDtlsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastUpdate;
    private javax.swing.JLabel lastUpdateValue;
    private javax.swing.JLabel lblAvail;
    private javax.swing.JLabel lblCarSeatNo;
    private javax.swing.JLabel lblMainCerti;
    // End of variables declaration//GEN-END:variables
}
